selenium:
  container_name: selenium
  image: selenium/standalone-firefox
  ports:
   - "4444:4444"
  privileged: true
web:
  container_name: web
  build: .
  links:
    - selenium:selenium
  ports:
   - "8080:8080"
nginx:
  build: ./nginx
  container_name: nginx
  ports:
    - "80:80"
  links:
    - web:web
