selenium:
  container_name: selenium
  build: ./selenium
  ports:
   - "4444:4444"
  privileged: true
  restart: always
api:
  container_name: api
  build: ./api
  links:
    - selenium:selenium
  ports:
   - "8080:8080"
  restart: always
web:
  container_name: web
  build: ./web
  ports:
   - "8081:8081"
  restart: always
nginx:
  build: ./nginx
  container_name: nginx
  ports:
    - "80:80"
  links:
    - api:api
    - web:web
  restart: always
