selenium:
  container_name: selenium
  image: selenium/standalone-firefox
  ports:
   - "4444:4444"
  privileged: true
service:
  container_name: service
  build: ./service
  links:
    - selenium
  environment:
    PORT: 3000
  ports:
   - "3000:3000"
