selenium:
  container_name: selenium
  build: ./selenium
  ports:
   - "4444:4444"
  privileged: true
  restart: always
api:
  container_name: api
  build: ./api
  links:
    - selenium:selenium
  ports:
   - "8080:8080"
  restart: always
postgres:
  container_name: postgres
  image: postgres:9.4.5
  environment:
    POSTGRES_USER: "${POSTGRES_USER}"
    POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
  ports:
    - "5432:5432"
  volumes:
    - pagereport-postgres:/var/lib/postgresql/data
web:
  container_name: web
  build: ./web
  environment:
    DATABASE_URL: "${DATABASE_URL}"
    PORT: "8081"
  ports:
   - "8081:8081"
  links:
    - postgres:postgres
  volumes:
    - "./web:/app"
  restart: always
nginx:
  build: ./nginx
  container_name: nginx
  ports:
    - "80:80"
  links:
    - api:api
    - web:web
  restart: always
