- hosts: pagereport
  sudo: true
  remote_user: root
  roles:
    - role: angstwad.docker_ubuntu

- hosts: pagereport
  sudo: true
  remote_user: root
  vars:
    docker_compose_version: 1.5.2
    docker_compose_bin: /usr/local/bin/docker-compose
  tasks:
  - name: download binary
    get_url: >
      dest={{docker_compose_bin}}
      url=https://github.com/docker/compose/releases/download/{{docker_compose_version}}/docker-compose-Linux-x86_64
  - name: set kbinary permissions
    file: dest={{docker_compose_bin}} state=file mode=755
